---
title: "Reproducible Research: Why and How"
subtitle: "SER Pre-Conference Workshop"  
author: "Sam Harper"
institute: " <br> </br>"
date: "2020-10-30"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [xaringan-themer.css, style.css]
    nature:
      beforeInit: "macros.js"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(here)
library(xaringan)
```

```{r xaringan-themer, include=FALSE}
library(xaringanthemer)
style_xaringan(text_color = "#000000", header_color = "#737373", text_font_size = "24px",  text_font_family = "'Lucida Sans'", header_font_google = google_font("Source Sans Pro"), header_font_weight="lighter", title_slide_background_color =  "#ffffff", title_slide_text_color = "#000000", link_color = "#0000ee", footnote_font_size = "0.5em")
```

## 0. Introduction ([lecture](slides/00-intro/00-intro.html))

## 1. Scientific Integrity Problems ([lecture](slides/01-integrity/01-integrity.html))

## 2. Design Solutions ([lecture](slides/02-design/02-design.html))

## 3. Analytic Solutions ([lecture](slides/03-analytic/03-analytic.html))

## 4. Dissemination Solutions ([lecture](slides/04-dissemination/04-dissemination.html))

## 5. Reproducible Example ([OSF repository for demo](https://osf.io/3fcxd/))